const songs = [
        {
          title: "Believer",
          artist: "Imagine Dragons",
          coverUrl: "https://example.com/path_to_believer_cover.jpg",
          thumbUrl: "https://example.com/path_to_believer_thumb.jpg",
          audio: "/sounds/believer.mp3",
          palette: "coral",
        },
        {
          title: "Devil Eyes",
          artist: "Hippie Sabotage",
          coverUrl: "https://example.com/path_to_devil_eyes_cover.jpg",
          thumbUrl: "https://example.com/path_to_devil_eyes_thumb.jpg",
          audio: "/sounds/devil_eyes.mp3",
          palette: "coral", 
        },
        {
          title: "Fairytale",
          artist: "Alexander Rybak",
          coverUrl: "https://example.com/path_to_fairytale_cover.jpg",
          thumbUrl: "https://example.com/path_to_fairytale_thumb.jpg",
          audio: "/sounds/fairy_tail.mp3",
          palette: "coral",
        },
        {
          title: "Old Town Road",
          artist: "Lil Nas X",
          coverUrl: "https://example.com/path_to_old_town_road_cover.jpg",
          thumbUrl: "https://example.com/path_to_old_town_road_thumb.jpg",
          audio: "/sounds/old_town.mp3",
          palette: "coral", 
        },
        {
          title: "Shape Of You",
          artist: "Ed Sheeran",
          coverUrl: "https://example.com/path_to_shape_of_you_cover.jpg",
          thumbUrl: "https://example.com/path_to_shape_of_you_thumb.jpg",
          audio: "/sounds/shape_of_you.mp3",
          palette: "coral", 
        },
        {
          title: "The Nights",
          artist: "Avicii",
          coverUrl: "https://example.com/path_to_the_nights_cover.jpg",
          thumbUrl: "https://example.com/path_to_the_nights_thumb.jpg",
          audio: "/sounds/the_nights.mp3",
          palette: "coral", 
        },
        {
          title: "Thrift Shop",
          artist: "Macklemore & Ryan Lewis",
          coverUrl: "https://example.com/path_to_thrift_shop_cover.jpg",
          thumbUrl: "https://example.com/path_to_thrift_shop_thumb.jpg",
          audio: "/sounds/thrift_shop.mp3",
          palette: "coral", 
        },
        {
          title: "Venom (Remix)",
          artist: "Eminem",
          coverUrl: "https://example.com/path_to_venom_cover.jpg",
          thumbUrl: "https://example.com/path_to_venom_thumb.jpg",
          audio: "/sounds/venom.mp3",
          palette: "coral",
        },
        {
          title: "Pretty Little Baby",
          artist: "Connie Francis",
          coverUrl: "https://example.com/path_to_venom_cover.jpg",
          thumbUrl: "https://example.com/path_to_venom_thumb.jpg",
          audio: "/sounds/Pretty_Little_Baby.mp3",
          palette: "coral",
        }
];

export default songs;
